// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"myapp/internal/user/application/commands"
	"myapp/internal/user/infrastructure/repositories"
	"myapp/internal/user/interface/grpc"
)

// Injectors from wire.go:

func InitializeUserHandlers() *grpc.UserHandler {
	gormUserRepository := repositories.NewGormUserRepository()
	loginUserHandler := commands.NewLoginUserHandler(gormUserRepository)
	userHandler := grpc.NewUserHandler(loginUserHandler)
	return userHandler
}
