// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"myapp/internal/user/application/usecases"
	"myapp/internal/user/infrastructure/repositories"
	"myapp/internal/user/interface/grpc"
)

// Injectors from wire.go:

func InitializeUserHandler() (*grpc.UserHandler, error) {
	userRepository := repositories.NewGormRepository()
	loginUserUsecase := usecases.NewLoginUserUsecase(userRepository)
	handshakeUsecase := usecases.NewHandshakeUsecase(userRepository)
	userHandler := grpc.NewUserHandler(loginUserUsecase, handshakeUsecase)
	return userHandler, nil
}
