// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"myapp/internal/user/application"
	"myapp/internal/user/infrastructure/repository"
)

// Injectors from wire.go:

func InitializeLoginUsecase() *application.LoginUserUsecase {
	gormUserRepository := repository.NewGormUserRepository()
	loginUserUsecase := application.NewLoginUserUsecase(gormUserRepository)
	return loginUserUsecase
}
